services:
  php-fpm:
    image: danog/madelineproto@sha256:5fa71c91868312b6da38ce108ccfbf99a3aef71d33dde29bb597cf15b10886c6
    restart: always
    init: true
    depends_on:
      mysqldb:
        condition: service_healthy
    volumes:
      - ./app:/app
    command: php-fpm
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
  
  caddy:
    image: caddy:2.9.1-alpine
    restart: always
    depends_on:
      - php-fpm
    ports:
      - $LOCAL_PORT:80/tcp
    volumes:
      - ./app:/app
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy_data:/data
      - ./caddy_config:/config
  mysqldb:
    image: mysql:8.0.31
    restart: unless-stopped
    env_file: ./.env
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
      - TZ=Europe/Rome
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD' ]
      timeout: 5s
      retries: 55
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db_vol:/var/lib/mysql
      - ./adder.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db_vol: